# Generated by Django 5.2.16 on 2026-08-02 10:11

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LearnerProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("learner_key", models.UUIDField(unique=True)),
                (
                    "ai_experience",
                    models.CharField(
                        choices=[
                            ("none", "使ったことがない"),
                            ("tried", "数回だけ使った"),
                            ("occasional", "ときどき使う"),
                            ("regular", "日常的に使う"),
                        ],
                        max_length=20,
                    ),
                ),
                ("job_category", models.CharField(max_length=100)),
                ("pain_point", models.CharField(max_length=200)),
                ("learning_goal", models.CharField(blank=True, max_length=200)),
                (
                    "detail_preference",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("brief", "みじかく"),
                            ("standard", "ふつう"),
                            ("detailed", "くわしく"),
                        ],
                        max_length=20,
                    ),
                ),
                ("used_ai_services", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UseCaseRecommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("job_category", models.CharField(max_length=100)),
                ("pain_point", models.CharField(max_length=200)),
                ("lesson_id", models.CharField(max_length=100)),
                ("use_case_id", models.CharField(max_length=100)),
                ("headline", models.CharField(max_length=100)),
                ("priority", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["priority"],
                "indexes": [
                    models.Index(
                        fields=["job_category", "pain_point"],
                        name="profiles_us_job_cat_2460a6_idx",
                    )
                ],
            },
        ),
    ]
