# Generated by Django 5.2.16 on 2026-08-19 04:37

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("admin_view", "管理画面で閲覧"),
                            ("admin_change", "管理画面で変更"),
                            ("admin_delete", "管理画面で削除"),
                            ("self_data_delete", "本人が学習データを削除"),
                            ("self_account_delete", "本人がアカウントを削除"),
                            ("retention_prune", "保存期間切れの削除"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("actor", models.CharField(blank=True, max_length=150)),
                ("target_model", models.CharField(blank=True, max_length=100)),
                ("target_id", models.CharField(blank=True, max_length=100)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("detail", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "verbose_name": "操作記録",
                "verbose_name_plural": "操作記録",
                "ordering": ["-at"],
                "indexes": [
                    models.Index(
                        fields=["actor", "at"], name="ops_auditlo_actor_2f10e0_idx"
                    ),
                    models.Index(
                        fields=["target_model", "at"],
                        name="ops_auditlo_target__70531d_idx",
                    ),
                ],
            },
        ),
    ]
