# Generated by Django 5.2.17 on 2026-08-21 02:47

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AiUsageLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("guest_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("lesson_id", models.CharField(blank=True, max_length=100)),
                ("recipe_id", models.CharField(blank=True, max_length=100)),
                ("task_type", models.CharField(blank=True, max_length=60)),
                ("provider", models.CharField(blank=True, max_length=40)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("image_count", models.PositiveIntegerField(default=0)),
                (
                    "estimated_cost_usd",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                ("credit_consumed", models.PositiveIntegerField(default=0)),
                ("success", models.BooleanField(default=True)),
                ("error_type", models.CharField(blank=True, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_usage_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI利用ログ",
                "verbose_name_plural": "AI利用ログ",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["task_type", "created_at"],
                        name="ai_aiusagel_task_ty_9f6fb9_idx",
                    ),
                    models.Index(
                        fields=["provider", "created_at"],
                        name="ai_aiusagel_provide_06677d_idx",
                    ),
                ],
            },
        ),
    ]
