# Generated by Django 5.2.17 on 2026-08-21 02:47

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0003_course_availability_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AiTaskPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_type", models.CharField(max_length=60, unique=True)),
                ("credit_cost", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("note", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name": "AI機能ごとのCredit消費量",
                "verbose_name_plural": "AI機能ごとのCredit消費量",
                "ordering": ("task_type",),
            },
        ),
        migrations.CreateModel(
            name="LearningPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URLと保存に使う名前", max_length=80, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "short_description",
                    models.CharField(
                        blank=True, help_text="一覧カードに出す1行説明", max_length=200
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=60)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "初級"),
                            ("intermediate", "中級"),
                            ("advanced", "上級"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("free", "無料"),
                            ("one_time", "買い切り"),
                            ("subscription", "受け放題"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "下書き"),
                            ("review", "確認中"),
                            ("published", "公開"),
                            ("archived", "取り下げ"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "availability_status",
                    models.CharField(
                        choices=[
                            ("available", "利用できる"),
                            ("coming_soon", "近日公開"),
                        ],
                        default="coming_soon",
                        max_length=20,
                        verbose_name="利用可能状態",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "estimated_total_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "badge_name",
                    models.CharField(
                        blank=True, help_text="完走したときの証の名前", max_length=120
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "学習パス",
                "verbose_name_plural": "学習パス",
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(blank=True, max_length=60)),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("free", "無料"),
                            ("one_time", "買い切り"),
                            ("subscription", "受け放題"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "下書き"),
                            ("review", "確認中"),
                            ("published", "公開"),
                            ("archived", "取り下げ"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "availability_status",
                    models.CharField(
                        choices=[
                            ("available", "利用できる"),
                            ("coming_soon", "近日公開"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="利用可能状態",
                    ),
                ),
                ("example_input", models.TextField(blank=True)),
                ("example_output", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "レシピ",
                "verbose_name_plural": "レシピ（こんな使い方もできます）",
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="CreditWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.IntegerField(default=0)),
                ("lifetime_earned", models.IntegerField(default=0)),
                ("lifetime_spent", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Credit残高",
                "verbose_name_plural": "Credit残高",
            },
        ),
        migrations.CreateModel(
            name="PathRewardMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("required_stamp_count", models.PositiveIntegerField()),
                ("reward_credits", models.PositiveIntegerField(default=0)),
                ("badge_name", models.CharField(blank=True, max_length=120)),
                ("order", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                (
                    "learning_path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="rewards.learningpath",
                    ),
                ),
            ],
            options={
                "verbose_name": "節目の特典",
                "verbose_name_plural": "節目の特典",
                "ordering": ("required_stamp_count",),
            },
        ),
        migrations.CreateModel(
            name="RecipeLearningPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "learning_path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_links",
                        to="rewards.learningpath",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="path_links",
                        to="rewards.recipe",
                    ),
                ),
            ],
            options={
                "verbose_name": "レシピの掲載パス",
                "verbose_name_plural": "レシピの掲載パス",
            },
        ),
        migrations.CreateModel(
            name="RecipeRequiredLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "required",
                    models.BooleanField(
                        default=True,
                        help_text="False なら「あるとなお良い」程度の任意扱い",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="required_by_recipes",
                        to="catalog.lesson",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="required_lessons",
                        to="rewards.recipe",
                    ),
                ),
            ],
            options={
                "verbose_name": "レシピの必要スキル",
                "verbose_name_plural": "レシピの必要スキル",
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="StampDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stamp_type",
                    models.CharField(
                        choices=[
                            ("lesson", "レッスン完了"),
                            ("practical_task", "実践課題完了"),
                            ("recipe", "レシピを試した"),
                            ("path_challenge", "パスの課題完了"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("order", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                (
                    "learning_path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stamp_definitions",
                        to="rewards.learningpath",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalog.lesson",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="rewards.recipe",
                    ),
                ),
            ],
            options={
                "verbose_name": "スタンプ定義",
                "verbose_name_plural": "スタンプ定義",
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="UserRewardClaim",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("claimed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "milestone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="rewards.pathrewardmilestone",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reward_claims",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "節目特典の受け取り",
                "verbose_name_plural": "節目特典の受け取り",
                "ordering": ["claimed_at"],
            },
        ),
        migrations.CreateModel(
            name="UserStamp",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("learner_key", models.UUIDField(db_index=True)),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stamp_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earned",
                        to="rewards.stampdefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "獲得スタンプ",
                "verbose_name_plural": "獲得スタンプ",
                "ordering": ["earned_at"],
            },
        ),
        migrations.CreateModel(
            name="CreditTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("reward", "報酬"),
                            ("consume", "消費"),
                            ("adjustment", "調整"),
                            ("purchase", "購入"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.IntegerField()),
                ("reason", models.CharField(blank=True, max_length=200)),
                ("source_type", models.CharField(blank=True, max_length=40)),
                ("source_id", models.CharField(blank=True, max_length=100)),
                ("balance_after", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Creditの動き",
                "verbose_name_plural": "Creditの動き",
                "ordering": ["created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("source_id__gt", ""), ("source_type__gt", "")
                        ),
                        fields=("user", "source_type", "source_id"),
                        name="uniq_credit_source",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LearningPathLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "day_number",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="「Day 3」のように出す。無ければ出さない",
                        null=True,
                    ),
                ),
                ("is_required", models.BooleanField(default=True)),
                (
                    "stamp_eligible",
                    models.BooleanField(
                        default=True,
                        help_text="このLessonを完了したとき、このPathのスタンプを埋めるか",
                    ),
                ),
                (
                    "learning_path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="path_lessons",
                        to="rewards.learningpath",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="path_memberships",
                        to="catalog.lesson",
                    ),
                ),
            ],
            options={
                "verbose_name": "パスのレッスン",
                "verbose_name_plural": "パスのレッスン",
                "ordering": ("order", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("learning_path", "lesson"), name="uniq_path_lesson"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="pathrewardmilestone",
            constraint=models.UniqueConstraint(
                fields=("learning_path", "required_stamp_count"),
                name="uniq_path_milestone_count",
            ),
        ),
        migrations.AddConstraint(
            model_name="recipelearningpath",
            constraint=models.UniqueConstraint(
                fields=("recipe", "learning_path"), name="uniq_recipe_path"
            ),
        ),
        migrations.AddConstraint(
            model_name="reciperequiredlesson",
            constraint=models.UniqueConstraint(
                fields=("recipe", "lesson"), name="uniq_recipe_lesson"
            ),
        ),
        migrations.AddConstraint(
            model_name="userrewardclaim",
            constraint=models.UniqueConstraint(
                fields=("user", "milestone"), name="uniq_user_milestone_claim"
            ),
        ),
        migrations.AddConstraint(
            model_name="userstamp",
            constraint=models.UniqueConstraint(
                fields=("learner_key", "stamp_definition"), name="uniq_learner_stamp"
            ),
        ),
    ]
