# Generated by Django 5.2.17 on 2026-08-27 00:41

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_lesson_thumbnail"),
        ("rewards", "0002_seed_foundation_path"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="一般用語の英語。図鑑の並びと、獲得記録の照合に使う",
                        max_length=60,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="表示名（日本語）", max_length=60)),
                (
                    "one_line",
                    models.CharField(help_text="一覧に出す1行", max_length=80),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="もう少し詳しく"),
                ),
                (
                    "example",
                    models.CharField(
                        blank=True,
                        help_text="「取引先向けに丁寧にして」のような実例",
                        max_length=200,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI技",
                "verbose_name_plural": "AI技",
                "ordering": ("order", "slug"),
            },
        ),
        migrations.CreateModel(
            name="AiSkillLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_links",
                        to="catalog.lesson",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_links",
                        to="rewards.aiskill",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI技のレッスン",
                "verbose_name_plural": "AI技のレッスン",
                "ordering": ("order", "id"),
            },
        ),
        migrations.AddField(
            model_name="aiskill",
            name="lessons",
            field=models.ManyToManyField(
                blank=True,
                related_name="ai_skills",
                through="rewards.AiSkillLesson",
                to="catalog.lesson",
            ),
        ),
        migrations.CreateModel(
            name="XpEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("learner_key", models.UUIDField(db_index=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("lesson_completed", "レッスン完了"),
                            ("ai_skill_acquired", "AI技の習得"),
                            ("course_checkpoint", "コースの節目"),
                        ],
                        max_length=30,
                    ),
                ),
                ("source_id", models.CharField(max_length=100)),
                ("amount", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "XPの増加",
                "verbose_name_plural": "XPの増加",
                "ordering": ["created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("learner_key", "kind", "source_id"),
                        name="uniq_xp_source",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="aiskilllesson",
            constraint=models.UniqueConstraint(
                fields=("skill", "lesson"), name="uniq_skill_lesson"
            ),
        ),
    ]
