"""AIPPO Level と、昇段のしくみ。

技（`AiSkill`）と取得記録（`SkillProgress`）はもとからある。ここで足す
のは**その上の層**だけ——段、段ごとの要件、昇段の実践問題、挑戦の記録、
そして「その人がいまどの段か」。

技の取得記録には触らない。診断で上の段から始めた人も、技は未取得の
まま置く（`UserLevel.reached_by`）。
"""

# Generated by Django 5.2.17 on 2026-09-20 15:58

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0004_add_paused_availability"),
    ]

    operations = [
        migrations.CreateModel(
            name="AippoLevel",
            fields=[
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        help_text="1〜5。診断の段階と同じ番号",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="短い名前（「頼む」）", max_length=40),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="どこまで使える段か（1行）", max_length=120
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "AIPPO Level",
                "verbose_name_plural": "AIPPO Level",
                "ordering": ("number",),
            },
        ),
        migrations.CreateModel(
            name="RankUpChallenge",
            fields=[
                (
                    "level",
                    models.OneToOneField(
                        help_text="この問題を通ると上がる段",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="challenge",
                        serialize=False,
                        to="rewards.aippolevel",
                    ),
                ),
                ("title", models.CharField(max_length=80)),
                (
                    "scenario",
                    models.TextField(help_text="場面。ここを読んで指示文を書く"),
                ),
                (
                    "checks",
                    models.JSONField(
                        default=list,
                        help_text='["purpose", "audience", "condition", "format"]',
                    ),
                ),
                ("estimated_minutes", models.PositiveSmallIntegerField(default=2)),
            ],
            options={
                "verbose_name": "昇段の実践問題",
                "verbose_name_plural": "昇段の実践問題",
            },
        ),
        migrations.CreateModel(
            name="UserLevel",
            fields=[
                ("learner_key", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "reached_by",
                    models.CharField(
                        choices=[
                            ("diagnosis", "診断で決まった開始地点"),
                            ("rankup", "実践問題を通って上がった"),
                        ],
                        default="diagnosis",
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="users",
                        to="rewards.aippolevel",
                    ),
                ),
            ],
            options={
                "verbose_name": "いまの Level",
                "verbose_name_plural": "いまの Level",
            },
        ),
        migrations.CreateModel(
            name="LevelRequirement",
            fields=[
                (
                    "level",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="requirement",
                        serialize=False,
                        to="rewards.aippolevel",
                    ),
                ),
                (
                    "required_skills",
                    models.ManyToManyField(
                        blank=True,
                        help_text="この段へ上がるのに要る技。全部そろって初めて挑戦できる",
                        related_name="required_for_levels",
                        to="rewards.aiskill",
                    ),
                ),
            ],
            options={
                "verbose_name": "昇段の条件",
                "verbose_name_plural": "昇段の条件",
            },
        ),
        migrations.CreateModel(
            name="ChallengeAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("learner_key", models.UUIDField(db_index=True)),
                ("passed", models.BooleanField()),
                ("missing", models.JSONField(default=list)),
                ("answer", models.TextField(blank=True, help_text="書いた指示文")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="rewards.rankupchallenge",
                    ),
                ),
            ],
            options={
                "verbose_name": "挑戦の記録",
                "verbose_name_plural": "挑戦の記録",
                "ordering": ("-created_at",),
            },
        ),
    ]
