# Generated by Django 5.2.16 on 2026-08-03 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URLと保存に使う名前", max_length=80, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("free", "無料"),
                            ("one_time", "買い切り"),
                            ("subscription", "受け放題"),
                        ],
                        default="free",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "下書き"),
                            ("review", "確認中"),
                            ("published", "公開"),
                            ("archived", "取り下げ"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "thumbnail",
                    models.CharField(
                        blank=True,
                        help_text="public/ からの道筋（例: /brand/app-icon.webp）",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "コース",
                "verbose_name_plural": "コース",
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="画面と記録で教材を指す名前。公開後は変えない",
                        max_length=80,
                        unique=True,
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        help_text="一覧に出す番号（Lesson 1 など）"
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                (
                    "goal",
                    models.CharField(
                        help_text="何ができるようになるか（1行）", max_length=200
                    ),
                ),
                (
                    "template",
                    models.CharField(
                        choices=[
                            ("outcome_first", "成果物ファースト（骨格から生成）"),
                            ("custom", "自由（ステップ行がそのまま中身）"),
                        ],
                        default="outcome_first",
                        max_length=20,
                    ),
                ),
                (
                    "outcome_title",
                    models.CharField(
                        blank=True,
                        help_text="今日つくるもの。最初の画面の見出し",
                        max_length=120,
                    ),
                ),
                ("outcome_description", models.CharField(blank=True, max_length=200)),
                (
                    "estimated_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="だいたいの所要時間。先が見えないと始めにくい",
                        null=True,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "初級"),
                            ("intermediate", "中級"),
                            ("advanced", "上級"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                (
                    "before_example",
                    models.TextField(blank=True, help_text="完成イメージの Before"),
                ),
                (
                    "after_example",
                    models.TextField(blank=True, help_text="完成イメージの After"),
                ),
                (
                    "learned_skills",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="今日できるようになること（文字列の配列）",
                    ),
                ),
                (
                    "outcomes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="進捗画面に出す、身についたこと",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        blank=True, default=list, help_text="診断からの推薦に使う"
                    ),
                ),
                ("uses_ai", models.BooleanField(default=True)),
                (
                    "mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("standard", "通常"),
                            ("model_comparison", "モデル比較"),
                        ],
                        help_text="空なら通常。将来のモデル比較コース用の目印",
                        max_length=20,
                    ),
                ),
                (
                    "ai_action",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='AIへの頼み方。例: {"action": "rewrite", "inputs": {...}}',
                    ),
                ),
                (
                    "sample_text",
                    models.TextField(
                        blank=True,
                        help_text="最初の1回で使う例文。空欄から始めさせない",
                    ),
                ),
                (
                    "quick_title",
                    models.CharField(
                        blank=True, help_text="最初に選ばせる唯一の問い", max_length=120
                    ),
                ),
                ("quick_instruction", models.CharField(blank=True, max_length=200)),
                (
                    "quick_key",
                    models.CharField(
                        blank=True,
                        help_text="その答えの保存先（audience など）",
                        max_length=60,
                    ),
                ),
                ("quick_options", models.JSONField(blank=True, default=list)),
                (
                    "quick_defaults",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="選ばせない条件の既定値。最初の1回を成立させるために埋める",
                    ),
                ),
                (
                    "working",
                    models.CharField(
                        blank=True,
                        help_text="送っているあいだに出す一言",
                        max_length=200,
                    ),
                ),
                (
                    "observation_options",
                    models.JSONField(
                        blank=True, default=list, help_text="空なら共通のものを使う"
                    ),
                ),
                (
                    "concept_cards",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="短い解説。3枚まで（超えた分は捨てる）",
                    ),
                ),
                (
                    "review_points",
                    models.JSONField(
                        blank=True, default=list, help_text="結果を見るときの着眼点"
                    ),
                ),
                ("real_task_label", models.CharField(blank=True, max_length=200)),
                ("real_task_placeholder", models.CharField(blank=True, max_length=200)),
                ("takeaway", models.CharField(blank=True, max_length=200)),
                ("next_suggestion", models.CharField(blank=True, max_length=200)),
                (
                    "fact_check",
                    models.BooleanField(
                        default=False,
                        help_text="数字や日付の確認をとくに促すか（比較・計画）",
                    ),
                ),
                (
                    "is_preview",
                    models.BooleanField(
                        default=False,
                        help_text="有料コースでも、ここまでは無料で見せる",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "下書き"),
                            ("review", "確認中"),
                            ("published", "公開"),
                            ("archived", "取り下げ"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="catalog.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "レッスン",
                "verbose_name_plural": "レッスン",
                "ordering": ("sort_order", "number", "id"),
            },
        ),
        migrations.CreateModel(
            name="LessonStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("override", "生成済みステップの上書き（step_key が一致）"),
                            ("lead_in", "骨格の前に置く"),
                            ("after_real_task", "「自分の文章」の直後に置く"),
                        ],
                        default="override",
                        help_text="成果物ファースト型のとき、この行をどこへ置くか",
                        max_length=20,
                    ),
                ),
                (
                    "step_key",
                    models.CharField(
                        help_text="ステップを指す名前。自由型では画面のid、成果物ファースト型では上書き先（quick_try など）",
                        max_length=60,
                    ),
                ),
                (
                    "step_type",
                    models.CharField(
                        blank=True,
                        help_text="画面の種類。上書きのときは空でよい",
                        max_length=40,
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        blank=True,
                        help_text="上の帯のどこか（outcome / try / compare / own）",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=120)),
                ("instruction", models.CharField(blank=True, max_length=200)),
                ("po_message", models.CharField(blank=True, max_length=300)),
                ("po_emotion", models.CharField(blank=True, max_length=20)),
                (
                    "input_key",
                    models.CharField(
                        blank=True,
                        help_text="入力の保存先。同じ名前を複数画面から読める",
                        max_length=60,
                    ),
                ),
                ("options", models.JSONField(blank=True, default=list)),
                ("placeholder", models.CharField(blank=True, max_length=200)),
                ("example", models.CharField(blank=True, max_length=300)),
                ("hints", models.JSONField(blank=True, default=list)),
                ("validation_rules", models.JSONField(blank=True, default=dict)),
                ("ai_action", models.JSONField(blank=True, default=dict)),
                (
                    "card",
                    models.JSONField(
                        blank=True, default=dict, help_text="短い解説の中身"
                    ),
                ),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("skill", models.CharField(blank=True, max_length=200)),
                (
                    "is_required",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                (
                    "is_skippable",
                    models.BooleanField(blank=True, default=None, null=True),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="catalog.lesson",
                    ),
                ),
            ],
            options={
                "verbose_name": "ステップ",
                "verbose_name_plural": "ステップ",
                "ordering": ("sort_order", "id"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("lesson", "step_key"), name="unique_step_key_per_lesson"
                    )
                ],
            },
        ),
    ]
