# Generated by Django 5.2.16 on 2026-08-04 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="availability_status",
            field=models.CharField(
                choices=[("available", "利用できる"), ("coming_soon", "近日公開")],
                default="coming_soon",
                help_text="出したうえで始められるか。既定は近日公開（うっかり始められないように）",
                max_length=20,
                verbose_name="利用可能状態",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="coming_soon_message",
            field=models.CharField(
                blank=True,
                help_text="近日公開のときに添える一言。空なら既定の文言",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="planned_release_date",
            field=models.DateField(
                blank=True,
                help_text="決まっているときだけ入れる。空なら日付を出さない",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "下書き"),
                    ("review", "確認中"),
                    ("published", "公開"),
                    ("archived", "取り下げ"),
                ],
                default="draft",
                help_text="一覧に出すかどうか。published だけが利用者に見える",
                max_length=20,
                verbose_name="公開状態",
            ),
        ),
    ]
