# Generated by Django 5.2.17 on 2026-08-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_lesson_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="outcome",
            field=models.CharField(
                blank=True,
                help_text="1文で。例: 文章・要約・整理・比較・画像まで、AIの基本が身につきます。",
                max_length=200,
                verbose_name="このコースでできるようになること",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="stage_key",
            field=models.SlugField(
                blank=True,
                help_text="同じ値が続くレッスンが1つのSTEPになる（例: ask / think / create）",
                max_length=40,
                verbose_name="STEPの識別子",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="stage_title",
            field=models.CharField(
                blank=True,
                help_text="そのSTEPの見出し（例: AIに頼んでみる）。同じ stage_key には同じ名前を入れる",
                max_length=60,
                verbose_name="STEPの名前",
            ),
        ),
    ]
