# Generated by Django 5.2.17 on 2026-08-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_course_outcome_lesson_stage_key_lesson_stage_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="condition_options",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="「条件を一つ足す」の選択肢。空なら共通のものを使う。共通のものは文章を直す言い回しなので、文章以外を扱う回では埋める",
            ),
        ),
    ]
