# Generated by Django 5.2.17 on 2026-08-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_lesson_condition_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonstep",
            name="primary_label",
            field=models.CharField(
                blank=True,
                help_text="画面の下のボタンの文言。空なら種類ごとの既定。押すと何が起きるかを書く（「次へ」は何も言っていない）",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="lessonstep",
            name="phase",
            field=models.CharField(
                blank=True,
                help_text="上の帯のどこか（outcome / try / compare / deepen / own）",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lessonstep",
            name="placement",
            field=models.CharField(
                choices=[
                    ("override", "生成済みステップの上書き（step_key が一致）"),
                    ("lead_in", "骨格の前に置く"),
                    ("deepen", "「自分の文章」の**前**に置く（技を深める）"),
                    ("after_real_task", "「自分の文章」の直後に置く"),
                ],
                default="override",
                help_text="成果物ファースト型のとき、この行をどこへ置くか",
                max_length=20,
            ),
        ),
    ]
