# Generated by Django 5.2.17 on 2026-08-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_step_primary_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="concept_skills",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="その解説で覚える技の名前。concept_cards と同じ並び。見出しはやさしい言い方（誰向けかを伝える）、ここは技の名前（ターゲット指定）。AI分野で普通に使う言葉にする",
            ),
        ),
    ]
