# Generated by Django 5.2.17 on 2026-08-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_lesson_concept_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="real_task_hints",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
