# Generated by Django 5.2.17 on 2026-08-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_lesson_real_task_hints"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="observe_reasons",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="lesson",
            name="observe_title",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
