# Generated by Django 5.2.17 on 2026-09-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_lesson_observe_reasons_lesson_observe_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="concept_anchors",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="lesson",
            name="observe_primary_label",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="lesson",
            name="sections",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
