# Generated by Django 5.2.17 on 2026-09-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0011_lesson_concept_anchors_lesson_observe_primary_label_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonstep",
            name="parts",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
