# Generated by Django 5.2.17 on 2026-09-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_lessonstep_parts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="availability_status",
            field=models.CharField(
                choices=[
                    ("available", "利用できる"),
                    ("coming_soon", "近日公開"),
                    ("paused", "一時停止"),
                ],
                default="coming_soon",
                help_text="出したうえで始められるか。既定は近日公開（うっかり開かないように）",
                max_length=20,
                verbose_name="利用可能状態",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="availability_status",
            field=models.CharField(
                choices=[
                    ("available", "利用できる"),
                    ("coming_soon", "近日公開"),
                    ("paused", "一時停止"),
                ],
                default="coming_soon",
                help_text="出したうえで始められるか。既定は近日公開（うっかり始められないように）",
                max_length=20,
                verbose_name="利用可能状態",
            ),
        ),
    ]
