# Generated by Django 5.2.16 on 2026-08-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthThrottle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(help_text="用途と相手のHMAC", max_length=96),
                ),
                ("window_start", models.DateTimeField()),
                ("count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "試行回数",
                "verbose_name_plural": "試行回数",
                "indexes": [
                    models.Index(
                        fields=["window_start"], name="accounts_au_window__998c7e_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scope", "window_start"),
                        name="uniq_auth_throttle_scope_window",
                    )
                ],
            },
        ),
    ]
