# Generated by Django 5.2.16 on 2026-08-19 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_passkey"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="remind_study",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="reminded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
