# Generated by Django 5.2.17 on 2026-09-03 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_totpdevice_recoverycode"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="unlimited_ai_runs",
            field=models.BooleanField(
                default=False,
                help_text="その人ぶんの1日の上限だけを外します。接続元ごと・全体の安全弁は外れません。",
                verbose_name="1日の上限を外す（動作確認用）",
            ),
        ),
    ]
