# Generated by Django 5.2.16 on 2026-08-02 10:11

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LearningSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("learner_key", models.UUIDField(db_index=True)),
                ("lesson_id", models.CharField(max_length=100)),
                (
                    "current_step",
                    models.CharField(
                        choices=[
                            ("INTRO", "Intro"),
                            ("SELECT_USE_CASE", "Select Use Case"),
                            ("FIRST_INPUT", "First Input"),
                            ("GENERATING", "Generating"),
                            ("REVIEW_RESULT", "Review Result"),
                            ("IMPROVE_INPUT", "Improve Input"),
                            ("REAL_TASK", "Real Task"),
                            ("REFLECTION", "Reflection"),
                            ("COMPLETE", "Complete"),
                        ],
                        default="INTRO",
                        max_length=50,
                    ),
                ),
                ("use_case_id", models.CharField(blank=True, max_length=100)),
                ("fill_in_values", models.JSONField(default=dict)),
                ("real_task_text", models.TextField(blank=True)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["learner_key", "lesson_id"],
                        name="lessons_lea_learner_cd129f_idx",
                    ),
                    models.Index(
                        fields=["completed_at"], name="lessons_lea_complet_006b7d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SkillProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("learner_key", models.UUIDField(db_index=True)),
                ("skill_key", models.CharField(max_length=100)),
                ("lesson_id", models.CharField(max_length=100)),
                ("acquired_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["acquired_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("learner_key", "skill_key"), name="uniq_learner_skill"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Survey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("answers", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey",
                        to="lessons.learningsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LearningEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("lesson_id", models.CharField(blank=True, max_length=100)),
                (
                    "step",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("INTRO", "Intro"),
                            ("SELECT_USE_CASE", "Select Use Case"),
                            ("FIRST_INPUT", "First Input"),
                            ("GENERATING", "Generating"),
                            ("REVIEW_RESULT", "Review Result"),
                            ("IMPROVE_INPUT", "Improve Input"),
                            ("REAL_TASK", "Real Task"),
                            ("REFLECTION", "Reflection"),
                            ("COMPLETE", "Complete"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("lesson_started", "Lesson Started"),
                            ("use_case_selected", "Use Case Selected"),
                            ("step_entered", "Step Entered"),
                            ("input_submitted", "Input Submitted"),
                            ("ai_run_requested", "Ai Run Requested"),
                            ("ai_run_succeeded", "Ai Run Succeeded"),
                            ("ai_run_failed", "Ai Run Failed"),
                            ("hint_shown", "Hint Shown"),
                            ("improvement_selected", "Improvement Selected"),
                            ("real_task_submitted", "Real Task Submitted"),
                            ("lesson_completed", "Lesson Completed"),
                            ("lesson_abandoned", "Lesson Abandoned"),
                            ("tutor_fallback_used", "Tutor Fallback Used"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("input_length", models.PositiveIntegerField(default=0)),
                ("hint_count", models.PositiveIntegerField(default=0)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("completed", models.BooleanField(default=False)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="lessons.learningsession",
                    ),
                ),
            ],
            options={
                "ordering": ["occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["session", "occurred_at"],
                        name="lessons_lea_session_f69502_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                ("lesson_id", models.CharField(max_length=100)),
                (
                    "step",
                    models.CharField(
                        choices=[
                            ("INTRO", "Intro"),
                            ("SELECT_USE_CASE", "Select Use Case"),
                            ("FIRST_INPUT", "First Input"),
                            ("GENERATING", "Generating"),
                            ("REVIEW_RESULT", "Review Result"),
                            ("IMPROVE_INPUT", "Improve Input"),
                            ("REAL_TASK", "Real Task"),
                            ("REFLECTION", "Reflection"),
                            ("COMPLETE", "Complete"),
                        ],
                        max_length=50,
                    ),
                ),
                ("user_input", models.TextField(blank=True)),
                ("conditions", models.JSONField(default=dict)),
                ("generated_output", models.TextField(blank=True)),
                ("tutor_message", models.CharField(blank=True, max_length=150)),
                (
                    "tutor_emotion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("neutral", "Neutral"),
                            ("question", "Question"),
                            ("thinking", "Thinking"),
                            ("hint", "Hint"),
                            ("warning", "Warning"),
                            ("celebrate", "Celebrate"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tutor_action",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("wait", "Wait"),
                            ("retry", "Retry"),
                            ("next", "Next"),
                            ("show_hint", "Show Hint"),
                            ("complete", "Complete"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tutor_origin",
                    models.CharField(
                        blank=True,
                        choices=[("ai", "Ai"), ("fallback", "Fallback")],
                        max_length=20,
                    ),
                ),
                ("hint_level", models.PositiveSmallIntegerField(default=0)),
                ("completed", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("timeout", "Timeout"),
                        ],
                        max_length=20,
                    ),
                ),
                ("model_name", models.CharField(blank=True, max_length=100)),
                ("token_usage", models.JSONField(blank=True, default=dict)),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="lessons.learningsession",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session", "sequence"), name="uniq_attempt_sequence"
                    )
                ],
            },
        ),
    ]
