# Generated by Django 5.2.16 on 2026-08-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiUsageCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(help_text="global、またはIPのHMAC", max_length=64),
                ),
                ("date", models.DateField()),
                ("count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["date"], name="lessons_aiu_date_ddbd28_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scope", "date"), name="uniq_ai_usage_scope_date"
                    )
                ],
            },
        ),
    ]
