# Generated by Django 5.2.16 on 2026-08-02 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0002_aiusagecounter"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationSummary",
            fields=[],
            options={
                "verbose_name": "検証サマリー",
                "verbose_name_plural": "検証サマリー",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("lessons.learningsession",),
        ),
    ]
