# Generated by Django 5.2.16 on 2026-08-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0003_verificationsummary"),
    ]

    operations = [
        migrations.AddField(
            model_name="attempt",
            name="action",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="attempt",
            name="error_kind",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="attempt",
            name="input_length",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="attempt",
            name="provider",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name="attempt",
            name="step",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="learningevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("course_started", "Course Started"),
                    ("course_completed", "Course Completed"),
                    ("step_viewed", "Step Viewed"),
                    ("option_selected", "Option Selected"),
                    ("text_entered", "Text Entered"),
                    ("prompt_preview_opened", "Prompt Preview Opened"),
                    ("ai_request_started", "Ai Request Started"),
                    ("ai_request_succeeded", "Ai Request Succeeded"),
                    ("ai_request_failed", "Ai Request Failed"),
                    ("hint_opened", "Hint Opened"),
                    ("real_task_started", "Real Task Started"),
                    ("real_task_skipped", "Real Task Skipped"),
                    ("privacy_warning_shown", "Privacy Warning Shown"),
                    ("privacy_warning_cancelled", "Privacy Warning Cancelled"),
                    ("privacy_warning_overridden", "Privacy Warning Overridden"),
                    ("lesson_started", "Lesson Started"),
                    ("use_case_selected", "Use Case Selected"),
                    ("step_entered", "Step Entered"),
                    ("input_submitted", "Input Submitted"),
                    ("ai_run_requested", "Ai Run Requested"),
                    ("ai_run_succeeded", "Ai Run Succeeded"),
                    ("ai_run_failed", "Ai Run Failed"),
                    ("hint_shown", "Hint Shown"),
                    ("improvement_selected", "Improvement Selected"),
                    ("real_task_submitted", "Real Task Submitted"),
                    ("lesson_completed", "Lesson Completed"),
                    ("lesson_abandoned", "Lesson Abandoned"),
                    ("tutor_fallback_used", "Tutor Fallback Used"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="learningevent",
            name="step",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="learningsession",
            name="current_step",
            field=models.CharField(default="INTRO", max_length=50),
        ),
    ]
