# Generated by Django 5.2.16 on 2026-08-04 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0004_attempt_action_attempt_error_kind_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("course_started", "Course Started"),
                    ("course_completed", "Course Completed"),
                    ("step_viewed", "Step Viewed"),
                    ("option_selected", "Option Selected"),
                    ("text_entered", "Text Entered"),
                    ("prompt_preview_opened", "Prompt Preview Opened"),
                    ("ai_request_started", "Ai Request Started"),
                    ("ai_request_succeeded", "Ai Request Succeeded"),
                    ("ai_request_failed", "Ai Request Failed"),
                    ("hint_opened", "Hint Opened"),
                    ("real_task_started", "Real Task Started"),
                    ("real_task_skipped", "Real Task Skipped"),
                    ("privacy_warning_shown", "Privacy Warning Shown"),
                    ("privacy_warning_cancelled", "Privacy Warning Cancelled"),
                    ("privacy_warning_overridden", "Privacy Warning Overridden"),
                    ("outcome_preview_viewed", "Outcome Preview Viewed"),
                    ("quick_try_started", "Quick Try Started"),
                    ("result_observation_submitted", "Result Observation Submitted"),
                    ("concept_card_viewed", "Concept Card Viewed"),
                    ("concept_card_skipped", "Concept Card Skipped"),
                    ("condition_added", "Condition Added"),
                    ("real_task_completed", "Real Task Completed"),
                    ("lesson_started", "Lesson Started"),
                    ("use_case_selected", "Use Case Selected"),
                    ("step_entered", "Step Entered"),
                    ("input_submitted", "Input Submitted"),
                    ("ai_run_requested", "Ai Run Requested"),
                    ("ai_run_succeeded", "Ai Run Succeeded"),
                    ("ai_run_failed", "Ai Run Failed"),
                    ("hint_shown", "Hint Shown"),
                    ("improvement_selected", "Improvement Selected"),
                    ("real_task_submitted", "Real Task Submitted"),
                    ("lesson_completed", "Lesson Completed"),
                    ("lesson_abandoned", "Lesson Abandoned"),
                    ("tutor_fallback_used", "Tutor Fallback Used"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
