# Generated by Django 5.2.16 on 2026-08-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0004_attempt_action_attempt_error_kind_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("course_started", "Course Started"),
                    ("course_completed", "Course Completed"),
                    ("step_viewed", "Step Viewed"),
                    ("option_selected", "Option Selected"),
                    ("text_entered", "Text Entered"),
                    ("prompt_preview_opened", "Prompt Preview Opened"),
                    ("ai_request_started", "Ai Request Started"),
                    ("ai_request_succeeded", "Ai Request Succeeded"),
                    ("ai_request_failed", "Ai Request Failed"),
                    ("hint_opened", "Hint Opened"),
                    ("real_task_started", "Real Task Started"),
                    ("real_task_skipped", "Real Task Skipped"),
                    ("privacy_warning_shown", "Privacy Warning Shown"),
                    ("privacy_warning_cancelled", "Privacy Warning Cancelled"),
                    ("privacy_warning_overridden", "Privacy Warning Overridden"),
                    ("diagnosis_started", "Diagnosis Started"),
                    ("diagnosis_completed", "Diagnosis Completed"),
                    ("lesson_viewed", "Lesson Viewed"),
                    ("first_result_generated", "First Result Generated"),
                    ("condition_added", "Condition Added"),
                    ("improved_result_generated", "Improved Result Generated"),
                    ("real_task_completed", "Real Task Completed"),
                    ("signup_prompt_viewed", "Signup Prompt Viewed"),
                    ("signup_started", "Signup Started"),
                    ("signup_completed", "Signup Completed"),
                    ("guest_data_migration_started", "Guest Data Migration Started"),
                    (
                        "guest_data_migration_completed",
                        "Guest Data Migration Completed",
                    ),
                    ("guest_data_migration_failed", "Guest Data Migration Failed"),
                    ("login_completed", "Login Completed"),
                    ("coming_soon_viewed", "Coming Soon Viewed"),
                    ("lesson_started", "Lesson Started"),
                    ("use_case_selected", "Use Case Selected"),
                    ("step_entered", "Step Entered"),
                    ("input_submitted", "Input Submitted"),
                    ("ai_run_requested", "Ai Run Requested"),
                    ("ai_run_succeeded", "Ai Run Succeeded"),
                    ("ai_run_failed", "Ai Run Failed"),
                    ("hint_shown", "Hint Shown"),
                    ("improvement_selected", "Improvement Selected"),
                    ("real_task_submitted", "Real Task Submitted"),
                    ("lesson_completed", "Lesson Completed"),
                    ("lesson_abandoned", "Lesson Abandoned"),
                    ("tutor_fallback_used", "Tutor Fallback Used"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
