# Generated by Django 5.2.16 on 2026-08-05 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0007_alter_learningevent_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiusagecounter",
            name="scope",
            field=models.CharField(
                help_text="global、またはIP・学習者のHMAC", max_length=128
            ),
        ),
    ]
