# Generated by Django 5.2.16 on 2026-08-19 04:13

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0008_alter_aiusagecounter_scope"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("learner_key", models.UUIDField(db_index=True)),
                ("lesson_id", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["learner_key", "created_at"],
                        name="lessons_boo_learner_33aca4_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("learner_key", "lesson_id"),
                        name="uniq_bookmark_learner_lesson",
                    )
                ],
            },
        ),
    ]
