# Generated by Django 5.2.17 on 2026-08-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0009_bookmark"),
    ]

    operations = [
        migrations.AddField(
            model_name="attempt",
            name="estimated_cost_usd",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=10, null=True
            ),
        ),
    ]
