# Generated by Django 5.2.17 on 2026-08-27 01:20

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0012_rename_skill_keys_to_ai_skills"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("learner_key", models.UUIDField(db_index=True)),
                ("lesson_id", models.CharField(max_length=100)),
                (
                    "title",
                    models.CharField(
                        help_text="既定は「{教材名}で作ったもの」。あとから直せる",
                        max_length=120,
                    ),
                ),
                ("output", models.TextField()),
                ("conditions", models.JSONField(blank=True, default=dict)),
                ("skills", models.JSONField(blank=True, default=list)),
                ("output_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "取っておいた成果物",
                "verbose_name_plural": "取っておいた成果物",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["learner_key", "-created_at"],
                        name="lessons_sav_learner_be89d5_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("learner_key", "lesson_id", "output_hash"),
                        name="uniq_saved_artifact",
                    )
                ],
            },
        ),
    ]
