# Generated by Django 5.2.17 on 2026-08-31 01:14

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0015_auth_funnel_events"),
    ]

    operations = [
        migrations.AlterField(
            model_name="learningevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("course_started", "Course Started"),
                    ("course_completed", "Course Completed"),
                    ("step_viewed", "Step Viewed"),
                    ("option_selected", "Option Selected"),
                    ("text_entered", "Text Entered"),
                    ("prompt_preview_opened", "Prompt Preview Opened"),
                    ("ai_request_started", "Ai Request Started"),
                    ("ai_request_succeeded", "Ai Request Succeeded"),
                    ("ai_request_failed", "Ai Request Failed"),
                    ("hint_opened", "Hint Opened"),
                    ("real_task_started", "Real Task Started"),
                    ("real_task_skipped", "Real Task Skipped"),
                    ("privacy_warning_shown", "Privacy Warning Shown"),
                    ("privacy_warning_cancelled", "Privacy Warning Cancelled"),
                    ("privacy_warning_overridden", "Privacy Warning Overridden"),
                    ("diagnosis_started", "Diagnosis Started"),
                    ("diagnosis_completed", "Diagnosis Completed"),
                    ("lesson_viewed", "Lesson Viewed"),
                    ("first_result_generated", "First Result Generated"),
                    ("condition_added", "Condition Added"),
                    ("improved_result_generated", "Improved Result Generated"),
                    ("real_task_completed", "Real Task Completed"),
                    ("signup_prompt_viewed", "Signup Prompt Viewed"),
                    ("signup_started", "Signup Started"),
                    ("signup_completed", "Signup Completed"),
                    ("guest_data_migration_started", "Guest Data Migration Started"),
                    (
                        "guest_data_migration_completed",
                        "Guest Data Migration Completed",
                    ),
                    ("guest_data_migration_failed", "Guest Data Migration Failed"),
                    ("login_completed", "Login Completed"),
                    ("ai_action_reserved", "Ai Action Reserved"),
                    ("ai_action_completed", "Ai Action Completed"),
                    ("ai_action_released", "Ai Action Released"),
                    ("guest_initial_credit_granted", "Guest Initial Credit Granted"),
                    ("daily_text_credit_granted", "Daily Text Credit Granted"),
                    (
                        "registration_text_bonus_granted",
                        "Registration Text Bonus Granted",
                    ),
                    (
                        "registration_image_bonus_granted",
                        "Registration Image Bonus Granted",
                    ),
                    ("day7_image_credit_granted", "Day7 Image Credit Granted"),
                    (
                        "day8_image_edit_credit_granted",
                        "Day8 Image Edit Credit Granted",
                    ),
                    ("guest_text_limit_reached", "Guest Text Limit Reached"),
                    ("register_now_clicked", "Register Now Clicked"),
                    ("wait_tomorrow_clicked", "Wait Tomorrow Clicked"),
                    ("auth_google_clicked", "Auth Google Clicked"),
                    ("auth_passkey_clicked", "Auth Passkey Clicked"),
                    ("returned_to_lesson", "Returned To Lesson"),
                    ("coming_soon_viewed", "Coming Soon Viewed"),
                    ("outcome_preview_viewed", "Outcome Preview Viewed"),
                    ("quick_try_started", "Quick Try Started"),
                    ("result_observation_submitted", "Result Observation Submitted"),
                    ("concept_card_viewed", "Concept Card Viewed"),
                    ("concept_card_skipped", "Concept Card Skipped"),
                    ("google_auth_failed", "Google Auth Failed"),
                    ("passkey_registration_failed", "Passkey Registration Failed"),
                    ("password_reset_requested", "Password Reset Requested"),
                    ("password_reset_sent", "Password Reset Sent"),
                    ("mission_completed", "Mission Completed"),
                    ("ai_skill_acquired", "Ai Skill Acquired"),
                    ("xp_earned", "Xp Earned"),
                    ("artifact_saved", "Artifact Saved"),
                    ("skill_dictionary_opened", "Skill Dictionary Opened"),
                    ("course_checkpoint_completed", "Course Checkpoint Completed"),
                    ("lesson_started", "Lesson Started"),
                    ("use_case_selected", "Use Case Selected"),
                    ("step_entered", "Step Entered"),
                    ("input_submitted", "Input Submitted"),
                    ("ai_run_requested", "Ai Run Requested"),
                    ("ai_run_succeeded", "Ai Run Succeeded"),
                    ("ai_run_failed", "Ai Run Failed"),
                    ("hint_shown", "Hint Shown"),
                    ("improvement_selected", "Improvement Selected"),
                    ("real_task_submitted", "Real Task Submitted"),
                    ("lesson_completed", "Lesson Completed"),
                    ("lesson_abandoned", "Lesson Abandoned"),
                    ("tutor_fallback_used", "Tutor Fallback Used"),
                    ("learning_path_started", "Learning Path Started"),
                    ("recipe_viewed", "Recipe Viewed"),
                    ("recipe_started", "Recipe Started"),
                    ("recipe_completed", "Recipe Completed"),
                    ("stamp_earned", "Stamp Earned"),
                    ("reward_claimed", "Reward Claimed"),
                    ("credit_earned", "Credit Earned"),
                    ("credit_consumed", "Credit Consumed"),
                    ("credit_insufficient", "Credit Insufficient"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="AiCreditBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("learner_key", models.UUIDField(db_index=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("text", "文章"),
                            ("image_generation", "画像を作る"),
                            ("image_edit", "画像を直す"),
                        ],
                        max_length=20,
                    ),
                ),
                ("available", models.PositiveIntegerField(default=0)),
                ("reserved", models.PositiveIntegerField(default=0)),
                ("consumed", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI無料枠の残り",
                "verbose_name_plural": "AI無料枠の残り",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("learner_key", "action_type"),
                        name="uniq_ai_credit_balance",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AiCreditGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("learner_key", models.UUIDField(db_index=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("text", "文章"),
                            ("image_generation", "画像を作る"),
                            ("image_edit", "画像を直す"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("guest_initial", "登録前の最初の持ち出し"),
                            ("registration_bonus", "登録したとき"),
                            ("daily", "日が変わったとき"),
                            ("day7_lesson", "Day7 に初めて着いたとき"),
                            ("day8_lesson", "Day8 に初めて着いたとき"),
                        ],
                        max_length=30,
                    ),
                ),
                ("on_date", models.DateField(blank=True, null=True)),
                ("amount", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "AI無料枠の付与",
                "verbose_name_plural": "AI無料枠の付与",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("learner_key", "action_type", "reason", "on_date"),
                        name="uniq_ai_credit_grant",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AiCreditLedger",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("learner_key", models.UUIDField(db_index=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("text", "文章"),
                            ("image_generation", "画像を作る"),
                            ("image_edit", "画像を直す"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reserved", "送っている最中"),
                            ("consumed", "使った"),
                            ("released", "戻した"),
                        ],
                        max_length=10,
                    ),
                ),
                ("request_id", models.UUIDField(db_index=True)),
                ("lesson_id", models.CharField(blank=True, max_length=60)),
                ("note", models.CharField(blank=True, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credit_entries",
                        to="lessons.attempt",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI無料枠の出入り",
                "verbose_name_plural": "AI無料枠の出入り",
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="lessons_aic_status_b09ec7_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("learner_key", "action_type", "request_id"),
                        name="uniq_ai_credit_request",
                    )
                ],
            },
        ),
    ]
