# Generated by Django 5.2.17 on 2026-08-31 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0016_ai_free_credits"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="aicreditgrant",
            name="uniq_ai_credit_grant",
        ),
        migrations.AddConstraint(
            model_name="aicreditgrant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("on_date__isnull", False)),
                fields=("learner_key", "action_type", "reason", "on_date"),
                name="uniq_ai_credit_grant_daily",
            ),
        ),
        migrations.AddConstraint(
            model_name="aicreditgrant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("on_date__isnull", True)),
                fields=("learner_key", "action_type", "reason"),
                name="uniq_ai_credit_grant_once",
            ),
        ),
    ]
