# Generated by Django 5.2.17 on 2026-08-31 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0018_attempt_quality_kind_alter_learningevent_event_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearnerTimezone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("learner_key", models.UUIDField(unique=True)),
                ("name", models.CharField(max_length=64)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("browser", "ブラウザが言ってきた"),
                            ("geo", "接続元から推した"),
                            ("default", "既定（Asia/Tokyo）"),
                        ],
                        max_length=10,
                    ),
                ),
                ("last_daily_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "学習者のタイムゾーン",
                "verbose_name_plural": "学習者のタイムゾーン",
            },
        ),
    ]
